### ISSUE TITLE
Add callbacks for data retrieval to /v1/embed-yourself

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NetExplorerProxy#111]
The new services in the oas are only to retrieve the already gathered (and preprocessed) data from the NEP cache.
The logic on how this data is gathered from devices via MWDI and written to the NEP cache is to be described in embed-yourself callbacks.

**Comment by kmohr-soprasteria** [comment]
Diagram 00x_CyclicOperationBasedDeviceListAndDataSync lists the following 4 forwardings:
1. PromptForEmbeddingCausesCyclicLoadingOfDeviceListFromMwdi
2. PromptForEmbeddingCausesCyclicUpdateOfNepDeviceList
3. PromptForEmbeddingCausesCyclicDeviceDataRetrievalFromMwdi
4. PromptForEmbeddingCausesCyclicDeletingUnconnectedDevicesFromNepCacheAfterRetentionExpiration

When /v1/embed-yourself is called, these callbacks have the following consequent-requests defined:
1. MWDI://v1/provide-list-of-connected-devices
2. ElasticSearch: this is to be omitted in the OAS
3. MWDI://core-model-1-4:network-control-domain=cache/control-construct={mount-name}?fields=*[fieldsFilter: nep-1-1-0-string-p-000]*: 
  - this is the callback, which gets the data from MWDI
  - the obtained data has to be filtered for relevant data (according to descriptions found in folder *additionalDescription*)
  - and be stored in the NEP cache (e.g. store data in separate database tables, so they can just be read when the new data provisioning services are called)
5. ElasticSearch: again, this is to be omitted in the OAS

**Comment by kmohr-soprasteria** [comment]
Schema for filtered CC data response:
- in OAS "additionalProperties: true" is default, i.e. when not provided it's assumed to be true
- in Postman validation this is not the case, i.e. the schema reference in Postman must include the "additionalProperties: true" explicitly, therefore it's already included in the OAS schema.

```
application/json:
  schema:
    description: 'Only relevant attributes listed, not all attributes are available for all devices'
    type: object
    required:
      - core-model-1-4:control-construct
    properties:
      core-model-1-4:control-construct:
        type: array
        items:
          type: object
          additionalProperties: true
          properties:
            #
            equipment-augment-1-0:control-construct-pac:
              type: object
              properties:
                device-model-name:
                  type: string
                external-label:
                  type: string
            #
            equipment-augment-1-0:protocol-collection:
              type: object
              properties:
                protocol:
                  type: array
                  items:
                    type: object
                    properties:
                      lldp-1-0:lldp-pac:
                        type: object
                        properties:
                          local-system-data:
                            type: object
                            properties:
                              system-name:
                                type: string
            #
            equipment:
              type: array
              items:
                type: object
                properties:
                  uuid:
                    type: string
                  local-id:
                    type: string
                  actual-equipment:
                    type: object
                    properties:
                      manufactured-thing:
                        type: object
                        properties:
                          equipment-type:
                            type: object
                            properties:
                              version:
                                type: string
                              description:
                                type: string
                              model-identifier:
                                type: string
                              part-type-identifier:
                                type: string
                              type-name:
                                type: string
                          manufacturer-properties:
                            type: object
                            properties:
                              manufacturer-name:
                                type: string
                              manufacturer-identifier:
                                type: string
            logical-termination-point:
              type: array
              items:
                type: object
                properties:
                  uuid:
                    type: string
                  operational-state:
                    type: string
                  ltp-augment-1-0:ltp-augment-pac:
                    type: object
                    properties:
                      original-ltp-name:
                        type: string
                  layer-protocol:
                    type: array
                    items:
                      type: object
                      additionalProperties: true
                      properties:
                        local-id:
                          type: string
                        administrative-state:
                          type: string
                        # not all interfaces may be available
                        # wire-interface
                        wire-interface-2-0:wire-interface-pac:
                          type: object
                          properties:
                            wire-interface-status:
                              type: object
                              properties:
                                interface-status:
                                  type: string
                                pmd-kind-cur:
                                  type: string
                            wire-interface-configuration:
                              type: object
                              properties:
                                interface-name:
                                  type: string
                                fixed-pmd-kind:
                                  type: string
                            wire-interface-capability:
                              type: object
                              properties:
                                supported-pmd-kind-list:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      pmd-name:
                                        type: string
                                      duplex:
                                        type: string
                                      speed:
                                        type: string
                        # ethernet-container
                        ethernet-container-2-0:ethernet-container-pac:
                          type: object
                          properties:
                            ethernet-container-historical-performances:
                              type: object
                              properties:
                                historical-performance-data-list:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      granularity-period:
                                        type: string
                                      period-end-time:
                                        type: string
                                      history-data-id:
                                        type: string
                                      performance-data:
                                        type: object
                                        properties:
                                          dropped-frames-input:
                                            type: integer
                                          dropped-frames-output:
                                            type: integer
                                          errored-frames-input:
                                            type: integer
                                          errored-frames-output:
                                            type: integer
                                          total-frames-input:
                                            type: string
                                          total-frames-output:
                                            type: string
                                          total-bytes-input:
                                            type: string
                                          total-bytes-output:
                                            type: string
                            ethernet-container-configuration:
                              type: object
                              properties:
                                interface-name:
                                  type: string
                                bundling-is-on:
                                  type: boolean
                            ethernet-container-status:
                              type: object
                              properties:
                                interface-status:
                                  type: string
                          # air interface
                          air-interface-2-0:air-interface-pac:
                            type: object
                            properties:
                              air-interface-historical-performances:
                                type: object
                                properties:
                                  historical-performances-data-list:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        granularity-period:
                                          type: string
                                        period-end-time:
                                          type: string
                                        history-data-id:
                                          type: string
                                        performance-data:
                                          type: object
                                          properties:
                                            ses:
                                              type: integer
                                            es: 
                                              type: integer
                                            unavailability:
                                              type: integer
                                            rx-level-min:
                                              type: integer
                                            rx-level-max:
                                              type: integer
                                            rx-level-avg:
                                              type: integer
                                            tx-level-min:
                                              type: integer
                                            tx-level-max:
                                              type: integer
                                            tx-level-avg:
                                              type: integer
                                            snir-min:
                                              type: integer
                                            snir-max:
                                              type: integer
                                            snir-avg:
                                              type: integer
                                            xpd-min:
                                              type: integer
                                            xpd-max:
                                              type: integer
                                            xpd-avg:
                                              type: integer
                                            time-xstates-list:
                                              type: array
                                              items:
                                                properties:
                                                  time:
                                                    type: integer
                                                  transmission-mode:
                                                    type: string
                                                description: 'filter for those array items, where time>0'
                              air-interface-configuration:
                                type: object
                                properties:
                                  transmission-mode-min:
                                    type: string
                                  transmission-mode-max:
                                    type: string
                                  power-is-on:
                                    type: boolean
                                  transmitter-is-on:
                                    type: boolean
                                  xpic-is-on:
                                    type: boolean
                              air-interface-status:
                                type: object
                                properties:
                                  interface-status:
                                    type: string
                              air-interface-capability:
                                type: object
                                properties:
                                  type-of-equipment:
                                    type: string
                                    transmission-mode-list:
                                      type: array
                                      items:
                                        type: object
                                        properties:
                                          tryansmission-mode-name:
                                            type: string
                                          symbol-rate-reduction-factor:
                                            type: integer
                                          channel-bandwidth:
                                            type: integer
                                          xpic-is-avail:
                                            type: boolean
                                          modulation-scheme-name-at-lct:
                                            type: string
                                          modulation-scheme:
                                            type: integer
                                          code-rate:
                                            type: integer
```

from the filter - not all properties are always present, therefore there's no required included except for the cc itself.
```
#equipment-augment-1-0:control-construct-pac(device-model-name;external-label);
#equipment-augment-1-0:protocol-collection
  #  (protocol(lldp-1-0:lldp-pac(local-system-data(system-name))));
#logical-termination-point(uuid;operational-state;ltp-augment-1-0:ltp-augment-pac(original-ltp-name);
  # layer-protocol(local-id;administrative-state;
    # wire-interface-2-0:wire-interface-pac(
      # wire-interface-configuration(interface-name;fixed-pmd-kind);
      # wire-interface-capability(supported-pmd-kind-list);
      # wire-interface-status(interface-status;pmd-kind-cur));
    # ethernet-container-2-0:ethernet-container-pac(
      # ethernet-container-historical-performances(
        # historical-performance-data-list(
            # granularity-period;period-end-time;history-data-id;
            # performance-data(dropped-frames-input;dropped-frames-output;errored-frames-input;errored-frames-output;total-frames-input;total-frames-output;total-bytes-input;total-bytes-output)));
      # ethernet-container-configuration(interface-name;bundling-is-on);
      # ethernet-container-status(interface-status));
    # air-interface-2-0:air-interface-pac(
      # air-interface-historical-performances(
          # historical-performance-data-list(
              # granularity-period;period-end-time;history-data-id;
              # performance-data(ses;es;unavailability;rx-level-min;rx-level-max;rx-level-avg;tx-level-min;tx-level-max;tx-level-avg;snir-min;snir-max;snir-avg;xpd-min;xpd-max;xpd-avg;time-xstates-list(time;transmission-mode))));
      # air-interface-configuration(transmission-mode-min;transmission-mode-max;power-is-on;transmitter-is-on;xpic-is-on);
      # air-interface-status(interface-status);
      # air-interface-capability(transmission-mode-list(transmission-mode-name;modulation-scheme-name-at-lct;modulation-scheme;channel-bandwidth;symbol-rate-reduction-factor;code-rate;xpic-is-avail);type-of-equipment))));
# equipment(uuid;local-id;
  # actual-equipment(manufactured-thing(equipment-type(version;description;model-identifier;part-type-identifier;type-name);manufacturer-properties(manufacturer-name;manufacturer-identifier))))
```

**Comment by kmohr-soprasteria** [comment]
shortened example derived from actual example by shortening included arrays and changing values manually to dummy values:
```
core-model-1-4:control-construct:
- logical-termination-point:
  - uuid: 'SYNC-1234567891'
    operational-state: 'core-model-1-4:OPERATIONAL_STATE_ENABLED'
    layer-protocol:
    - local-id: '1234567891'
      administrative-state: 'core-model-1-4:ADMINISTRATIVE_STATE_UNLOCKED'
    ltp-augment-1-0:ltp-augment-pac:
      original-ltp-name: 'E1 1/7/4D'
  - uuid: 'ETH-3456789123'
    operational-state: 'core-model-1-4:OPERATIONAL_STATE_ENABLED'
    layer-protocol:
    - local-id: '3456789123'
      ethernet-container-2-0:ethernet-container-pac:
        ethernet-container-status:
          interface-status: 'ethernet-container-2-0:INTERFACE_STATUS_TYPE_UP'
        ethernet-container-historical-performances:
          historical-performance-data-list:
          - granularity-period: 'ethernet-container-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
            period-end-time: '2025-01-07T22:00:00+01:00'
            performance-data:
              total-frames-input: -1
              total-bytes-input: 75120
              total-bytes-output: 15000
              total-frames-output: -1
              errored-frames-input: 0
              dropped-frames-input: 900
              dropped-frames-output: 0
              errored-frames-output: 0
            history-data-id: 'History Data ID not defined.'
        ethernet-container-configuration:
          interface-name: '10PN1234_M2-2'
          bundling-is-on: false
      administrative-state: 'core-model-1-4:ADMINISTRATIVE_STATE_UNLOCKED'
    ltp-augment-1-0:ltp-augment-pac:
      original-ltp-name: 'LAN 1/5/3'
  - uuid: 'RF-2223335555'
    operational-state: 'core-model-1-4:OPERATIONAL_STATE_ENABLED'
    layer-protocol:
    - local-id: '2223335555'
      air-interface-2-0:air-interface-pac:
        air-interface-configuration:
          transmission-mode-min: '56000-16-v0'
          transmitter-is-on: true
          transmission-mode-max: '56000-256-v0'
          xpic-is-on: false
          power-is-on: true
        air-interface-status:
          interface-status: 'air-interface-2-0:INTERFACE_STATUS_TYPE_UP'
        air-interface-historical-performances:
          historical-performance-data-list:
          - granularity-period: 'air-interface-2-0:GRANULARITY_PERIOD_TYPE_PERIOD-15-MIN'
            period-end-time: '2025-01-07T08:30:00+01:00'
            history-data-id: 'History Data ID not defined.'
            performance-data:
              es: 5
              xpd-max: -99
              tx-level-max: 12
              ses: 10
              rx-level-max: -50
              snir-min: 40
              snir-avg: -99
              rx-level-avg: 99
              unavailability: 20
              time-xstates-list:
              - time: 901
                transmission-mode: '56000-32-v0'
              - time: 0
                transmission-mode: '56000-64-v0'
              - time: 0
                transmission-mode: '56000-4-v0'
              - time: 0
                transmission-mode: '56000-16-v0'
              rx-level-min: -50
              xpd-min: -99
              xpd-avg: -99
              tx-level-min: 8
              tx-level-avg: 99
              snir-max: 41
        air-interface-capability:
          transmission-mode-list:
          - transmission-mode-name: '56000-32-v0'
            symbol-rate-reduction-factor: 1
            channel-bandwidth: 56000
            xpic-is-avail: true
            modulation-scheme-name-at-lct: '32 QAM'
            modulation-scheme: 32
            code-rate: 97
          type-of-equipment: 'RAU2 XYZ'
      administrative-state: 'core-model-1-4:ADMINISTRATIVE_STATE_UNLOCKED'
  - uuid: 'ETY-8888999912'
    operational-state: 'core-model-1-4:OPERATIONAL_STATE_ENABLED'
    layer-protocol:
    - local-id: '8888999912'
      wire-interface-2-0:wire-interface-pac:
        wire-interface-status:
          interface-status: 'wire-interface-2-0:INTERFACE_STATUS_TYPE_UP'
          pmd-kind-cur: '1000BASE_FD'
        wire-interface-configuration:
          interface-name: '123790001A_ge2/0'
          fixed-pmd-kind: '1000BASE_FD'
        wire-interface-capability:
          supported-pmd-kind-list:
          - pmd-name: '1000BASE_FD'
            duplex: 'wire-interface-2-0:DUPLEX_TYPE_FULL_DUPLEX'
            speed: '1000Mbit/s'
      administrative-state: 'core-model-1-4:ADMINISTRATIVE_STATE_UNLOCKED'
    ltp-augment-1-0:ltp-augment-pac:
      original-ltp-name: 'LAN 1/9/5'
  equipment:
  - uuid: '1919191919'
  - uuid: '1929394959'
    actual-equipment:
      manufactured-thing:
        equipment-type:
          version: 'R1C'
          description: 'Removable Memory Module'
          model-identifier: 'RMM'
          part-type-identifier: 'RYS 110 243/1'
          type-name: 'RMM'
        manufacturer-properties:
          manufacturer-name: 'SomeVendor'
  equipment-augment-1-0:control-construct-pac:
    device-model-name: 'SomeDeviceType'
    external-label: '100250001'
```
