### ISSUE TITLE
Add a new genericResponseProfile instance

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NetExplorerProxy#214]
Add a new profile instance for release 3 (1.1.1)

See example for release 2:
```

  - profile-name: 'GenericResponseProfile'
    uuid: 'nep-1-0-2-response-p-009'
    capability:
      operation-name: '/v1/inform-about-release-history-in-generic-representation'
      field-name-reference: '/core-model-1-4:control-construct/logical-termination-point=nep-1-1-0-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-list=2/release-number'
      description: 'Represents the second entry in the list of releases'
      datatype: string
    configuration:
      value-reference: '/core-model-1-4:control-construct/logical-termination-point=nep-1-1-0-http-s-000/layer-protocol=0/http-server-interface-1-0:http-server-interface-pac/http-server-interface-capability/release-list=2/changes'
```
